== Independent Validation Environment


=== Reference Environment

Link to a reference validation environment report with the golden versions and
configurations.

=== Executive Summary

The results indicate that the validation environment is compliant if results
 are equivalents to those in the reference validation environment report or
 non-compliant.

[cols=2*.^a]
|===


|
*hostname*
|
_not known_

|
*started*
|
2023-08-09 11:02:05+00:00

|
*duration (s)*
|
0.0

|
*test cases*
|
13

|
*test error*
|
2

|
*test failure*
|
0

|
*test success*
|
11
|===


=== Tests

==== GNSS

[%header,cols=5*.^a]
|===
|id|timestamp|duration (s)|result|reason


|
https://github.com/redhat-partner-solutions/vse-sync-test/tree/main/tests/sync/G.8272/environment/status/gnss/device-detected/wpc
|
2023-08-09 11:02:05+00:00
|
0
|
success
|
/dev/gnss0

|
https://github.com/redhat-partner-solutions/vse-sync-test/tree/main/tests/sync/G.8272/environment/version/gnss/model/wpc
|
2023-08-09 11:02:05+00:00
|
0
|
success
|
ZED-F9T

|
https://github.com/redhat-partner-solutions/vse-sync-test/tree/main/tests/sync/G.8272/environment/version/gnss/firmware/wpc
|
2023-08-09 11:02:05+00:00
|
0
|
success
|
TIM 2.20


|
https://github.com/redhat-partner-solutions/vse-sync-test/blob/main/tests/sync/G.8272/environment/version/gnss/protocol/wpc/
|
2023-08-09 11:02:05+00:00
|
0
|
success
|
29.20

|
https://github.com/redhat-partner-solutions/vse-sync-test/tree/main/tests/sync/G.8272/environment/status/gnss/antenna-connected/wpc
|
2023-08-09 11:02:05+00:00
|
0
|
success
|
Antenna is Connected

|
https://github.com/redhat-partner-solutions/vse-sync-test/blob/main/tests/sync/G.8272/environment/status/gnss/gpsfix-valid/wpc
|
2023-08-09 11:02:05+00:00
|
0
|
success
|
Signal Quality received valid

|
GNSS OTHERS...
|
2023-08-09 11:02:05+00:00
|
0
|
success
|

|===


==== DPLL

[%header,cols=5*.^a]
|===
|id|timestamp|duration (s)|result|reason


|
DPLL Firwmare is valid
|
2023-08-09 11:02:05+00:00
|
0
|
error
|
could not parse DPLL Firmware


|
DPLL Configuration is valid
|
2023-08-09 11:02:05+00:00
|
0
|
success
|

|===



==== NIC

[%header,cols=5*.^a]
|===
|id|timestamp|duration (s)|result|reason


|
Card driver is valid
|
2023-08-09 11:02:05+00:00
|
0
|
error
|
could not parse version v1.11.20.7


|
Card is valid NIC
|
2023-08-09 11:02:05+00:00
|
0
|
success
|


|
Card firmware is valid
|
2023-08-09 11:02:05+00:00
|
0
|
success
|

|===

==== PTP Operator


[%header,cols=5*.^a]
|===
|id|timestamp|duration (s)|result|reason

|
Opensift Cluster Version is valid
|
2023-08-09 11:02:05+00:00
|
0
|
success
|


|
PTP Operator Version is valid
|
2023-08-09 11:02:05+00:00
|
0
|
error
|
invalid version: 4.14.0-202307282303 < 4.14.0


|
GPSD Version is valid
|
2023-08-09 11:02:05+00:00
|
0
|
success
|


|
Configured for grand master
|
2023-08-09 11:02:05+00:00
|
0
|
success
|


|===

